//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibraryConversion_Client.ServiceReferenceConversiontemp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceConversiontemp.IConversionService")]
    public interface IConversionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/ConvertVersCelsius", ReplyAction="http://tempuri.org/IConversionService/ConvertVersCelsiusResponse")]
        double ConvertVersCelsius(double temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/ConvertVersCelsius", ReplyAction="http://tempuri.org/IConversionService/ConvertVersCelsiusResponse")]
        System.Threading.Tasks.Task<double> ConvertVersCelsiusAsync(double temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/ConversionVersFahr", ReplyAction="http://tempuri.org/IConversionService/ConversionVersFahrResponse")]
        double ConversionVersFahr(double temp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/ConversionVersFahr", ReplyAction="http://tempuri.org/IConversionService/ConversionVersFahrResponse")]
        System.Threading.Tasks.Task<double> ConversionVersFahrAsync(double temp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConversionServiceChannel : WcfServiceLibraryConversion_Client.ServiceReferenceConversiontemp.IConversionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConversionServiceClient : System.ServiceModel.ClientBase<WcfServiceLibraryConversion_Client.ServiceReferenceConversiontemp.IConversionService>, WcfServiceLibraryConversion_Client.ServiceReferenceConversiontemp.IConversionService {
        
        public ConversionServiceClient() {
        }
        
        public ConversionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConversionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ConvertVersCelsius(double temp) {
            return base.Channel.ConvertVersCelsius(temp);
        }
        
        public System.Threading.Tasks.Task<double> ConvertVersCelsiusAsync(double temp) {
            return base.Channel.ConvertVersCelsiusAsync(temp);
        }
        
        public double ConversionVersFahr(double temp) {
            return base.Channel.ConversionVersFahr(temp);
        }
        
        public System.Threading.Tasks.Task<double> ConversionVersFahrAsync(double temp) {
            return base.Channel.ConversionVersFahrAsync(temp);
        }
    }
}
