//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTemp.WebServiceTempSoap")]
    public interface WebServiceTempSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldResponse HelloWorld(Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldResponse> HelloWorldAsync(Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculerTemperarure", ReplyAction="*")]
        Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureResponse CalculerTemperarure(Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculerTemperarure", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureResponse> CalculerTemperarureAsync(Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculerTemperarureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculerTemperarure", Namespace="http://tempuri.org/", Order=0)]
        public Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureRequestBody Body;
        
        public CalculerTemperarureRequest() {
        }
        
        public CalculerTemperarureRequest(Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculerTemperarureRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string caseTemp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double valeur;
        
        public CalculerTemperarureRequestBody() {
        }
        
        public CalculerTemperarureRequestBody(string caseTemp, double valeur) {
            this.caseTemp = caseTemp;
            this.valeur = valeur;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculerTemperarureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculerTemperarureResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureResponseBody Body;
        
        public CalculerTemperarureResponse() {
        }
        
        public CalculerTemperarureResponse(Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculerTemperarureResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalculerTemperarureResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg;
        
        public CalculerTemperarureResponseBody() {
        }
        
        public CalculerTemperarureResponseBody(double CalculerTemperarureResult, string msg) {
            this.CalculerTemperarureResult = CalculerTemperarureResult;
            this.msg = msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTempSoapChannel : Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.WebServiceTempSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTempSoapClient : System.ServiceModel.ClientBase<Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.WebServiceTempSoap>, Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.WebServiceTempSoap {
        
        public WebServiceTempSoapClient() {
        }
        
        public WebServiceTempSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTempSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTempSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTempSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldResponse Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.WebServiceTempSoap.HelloWorld(Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldRequest inValue = new Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldRequest();
            inValue.Body = new Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldRequestBody();
            Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldResponse retVal = ((Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.WebServiceTempSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldResponse> Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.WebServiceTempSoap.HelloWorldAsync(Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldResponse> HelloWorldAsync() {
            Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldRequest inValue = new Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldRequest();
            inValue.Body = new Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.HelloWorldRequestBody();
            return ((Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.WebServiceTempSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureResponse Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.WebServiceTempSoap.CalculerTemperarure(Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureRequest request) {
            return base.Channel.CalculerTemperarure(request);
        }
        
        public double CalculerTemperarure(string caseTemp, double valeur, out string msg) {
            Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureRequest inValue = new Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureRequest();
            inValue.Body = new Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureRequestBody();
            inValue.Body.caseTemp = caseTemp;
            inValue.Body.valeur = valeur;
            Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureResponse retVal = ((Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.WebServiceTempSoap)(this)).CalculerTemperarure(inValue);
            msg = retVal.Body.msg;
            return retVal.Body.CalculerTemperarureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureResponse> Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.WebServiceTempSoap.CalculerTemperarureAsync(Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureRequest request) {
            return base.Channel.CalculerTemperarureAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureResponse> CalculerTemperarureAsync(string caseTemp, double valeur) {
            Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureRequest inValue = new Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureRequest();
            inValue.Body = new Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.CalculerTemperarureRequestBody();
            inValue.Body.caseTemp = caseTemp;
            inValue.Body.valeur = valeur;
            return ((Demo14_ServiceWebTemperature_Clint.ServiceReferenceTemp.WebServiceTempSoap)(this)).CalculerTemperarureAsync(inValue);
        }
    }
}
